version: 3

tasks:
  build:
    cmds:
      # - cargo build --artifact-dir bin --release # unstable
      - cargo build --release
      - go build -o bin ./cmd/gotext
      - go build -o bin ./cmd/setup-nsis
      - go build -o bin ./cmd/setup-upx
      - go build -o bin ./cmd/wails-build

  install:
    cmds:
      - go install ./cmd/gotext
      - go install ./cmd/setup-nsis
      - go install ./cmd/setup-upx
      - go install ./cmd/wails-build
      - cargo install --path .
