version: 3

tasks:
  build-gotext:
    dir: gotext
    cmds:
      - go build -o ../bin

  build-hibernate:
    dir: hibernate
    cmds:
      - go build -o ../bin

  build-setup-nsis:
    dir: setup-nsis
    cmds:
      - go build -o ../bin

  build-setup-upx:
    dir: setup-upx
    cmds:
      - go build -o ../bin

  build-wails-build:
    dir: wails-build
    cmds:
      - go build -o ../bin

  build:
    deps:
      - build-gotext
      - build-hibernate
      - build-setup-nsis
      - build-setup-upx
      - build-wails-build

  test:
    cmds:
      -